import { sqliteTable, text, integer } from 'drizzle-orm/sqlite-core'
import { imagePrompts } from './prompts'

export const generatedImages = sqliteTable('generated_images', {
  id: text('id').primaryKey(),
  promptId: text('prompt_id').notNull().references(() => imagePrompts.id, { onDelete: 'cascade' }),
  imageUrl: text('image_url').notNull(),
  thumbnailUrl: text('thumbnail_url'),
  imageProvider: text('image_provider').notNull(),
  width: integer('width'),
  height: integer('height'),
  dpi: integer('dpi').default(300),
  fileSize: integer('file_size'),
  mimeType: text('mime_type').notNull().default('image/png'),
  title: text('title'),
  description: text('description'),
  generationStatus: text('generation_status').notNull().default('pending'),
  providerJobId: text('provider_job_id'),
  errorMessage: text('error_message'),
  isSelected: integer('is_selected', { mode: 'boolean' }).notNull().default(false),
  status: text('status').notNull().default('active'),
  generationBatch: text('generation_batch'),
  s3KeyGenerated: text('s3_key_generated'),
  s3KeyBgRemoved: text('s3_key_bg_removed'),
  s3KeyUpscaled: text('s3_key_upscaled'),
  bgRemovedUrl: text('bg_removed_url'),
  bgRemovalStatus: text('bg_removal_status'),
  bgRemovalError: text('bg_removal_error'),
  upscaledUrl: text('upscaled_url'),
  upscaleStatus: text('upscale_status'),
  upscaleError: text('upscale_error'),
  metadata: text('metadata'),
  selectedVariationId: text('selected_variation_id'),
  createdAt: integer('created_at', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
})
