import { sqliteTable, text, integer } from 'drizzle-orm/sqlite-core'
import { users } from './users'

export const userSettings = sqliteTable('user_settings', {
  id: text('id').primaryKey(),
  userId: text('user_id').notNull().references(() => users.id).unique(),
  defaultAiProvider: text('default_ai_provider').notNull().default('gemini'),
  defaultImageProvider: text('default_image_provider').notNull().default('fal'),
  defaultUpscaleProvider: text('default_upscale_provider').notNull().default('local'),
  defaultBackgroundRemovalProvider: text('default_background_removal_provider').notNull().default('local-bg'),
  defaultFulfillmentProvider: text('default_fulfillment_provider').notNull().default('printify'),
  defaultTrendsProvider: text('default_trends_provider').notNull().default('google-trends'),
  geminiApiKey: text('gemini_api_key'),
  openaiApiKey: text('openai_api_key'),
  anthropicApiKey: text('anthropic_api_key'),
  xaiApiKey: text('xai_api_key'),
  groqApiKey: text('groq_api_key'),
  togetherApiKey: text('together_api_key'),
  deepinfraApiKey: text('deepinfra_api_key'),
  stageTextConfig: text('stage_text_config'),
  kreaApiKey: text('krea_api_key'),
  falApiKey: text('fal_api_key'),
  printifyApiKey: text('printify_api_key'),
  printifyShopId: text('printify_shop_id'),
  printfulApiKey: text('printful_api_key'),
  leonardoApiKey: text('leonardo_api_key'),
  photoroomApiKey: text('photoroom_api_key'),
  replicateApiToken: text('replicate_api_token'),
  rapidapiKey: text('rapidapi_key'),
  serpapiKey: text('serpapi_key'),
  searchapiKey: text('searchapi_key'),
  serperApiKey: text('serper_api_key'),
  defaultSearchProvider: text('default_search_provider'),
  useTrademarkApi: integer('use_trademark_api', { mode: 'boolean' }).notNull().default(false),
  useBrandRiskApi: integer('use_brand_risk_api', { mode: 'boolean' }).notNull().default(false),
  providerRegistryConfig: text('provider_registry_config'),
  defaultThemeCount: integer('default_theme_count').notNull().default(10),
  defaultWinnerCount: integer('default_winner_count').notNull().default(5),
  defaultPromptsPerTheme: integer('default_prompts_per_theme').notNull().default(5),
  defaultImagesPerPrompt: integer('default_images_per_prompt').notNull().default(1),
  maxProductVariants: integer('max_product_variants').notNull().default(5),
  defaultUpscaleFactor: integer('default_upscale_factor').notNull().default(2),
  createdAt: integer('created_at', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
  updatedAt: integer('updated_at', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
})
